### PR TITLE
feature/#684 rename pipeline to sequence

### PR DESCRIPTION
**Pull request by toan-quach**
https://app.zenhub.com/workspaces/taipy-613ef328affde6000ff77fb3/issues/gh/avaiga/taipy-core/684

### CODE REVIEW

**Review by jrobinAV — DISMISSED** [review]
Must be merged simultaneously with PRs on other repos

**Comment by toan-quach** [comment]
@jrobinAV @trgiangdo 
I think the tests are failing due to the `pipenv --skip-lock` issue that Giang raised yesterday. Can you help clarify this Giang? 
Also, it's not possible to generate the pyi file at the moment because we have to merge core first before we run pyi generation to propagate the renaming of `PipelineConfig` to `SequenceConfig`.

**Comment by trgiangdo** [comment]
We need to do something similar to this PR https://github.com/Avaiga/taipy-core/pull/733. That should help fixing the `--skip-lock` problem

**Comment by toan-quach** [comment]
working now thanks @trgiangdo !!!!!

**Review by trgiangdo — DISMISSED** [review]
I don't think we should worry about the .pyi file since it will be automatically update on the next PR.

We of course can wait for the PR on core to merge first, then rerun the action. It's up to you I guess 😂

**Review by jrobinAV — DISMISSED** [review]

**Review by trgiangdo — APPROVED** [review]

**Pull request merged**
