### PR TITLE
Fixtyping

### PR DESCRIPTION
**Pull request by Dr-Irv**
If you do 
```python
Config.scenarios["my_scenario_cfg"]
```
pyright says that `Config.scenarios` can't be subscripted.

That's because the PYI file doesn't declare that (and related methods) as class methods and as properties.

So this fixes that issue.

### CODE REVIEW

**Comment by jrobinAV** [comment]
Thank you for reporting this @Dr-Irv.

@joaoandre-avaiga Can you have a look at it?

**Comment by joaoandre-avaiga** [comment]
Hey @Dr-Irv Thanks for the contribution. We are trying to avoid updating `config.pyi` directly, because some of the properties and methods are injected from taipy-core. The update this .pyi file you can change the code of `stubs/generate_pyi.py`. 

For this particular problem, the issue is on the template defined for the `_generate_acessors` [method](https://github.com/Avaiga/taipy-config/blob/develop/stubs/generate_pyi.py#L126). Could you add the change there?

The final file is autogenerated by the GH action `Generate config.pyi` and automatically commited, so you don't have to worry about that.

Feel free to suggest improvements on this process as well if you hace any :)

**Comment by Dr-Irv** [comment]
> Hey @Dr-Irv Thanks for the contribution. We are trying to avoid updating `config.pyi` directly, because some of the properties and methods are injected from taipy-core. The update this .pyi file you can change the code of `stubs/generate_pyi.py`.
> 
> For this particular problem, the issue is on the template defined for the `_generate_acessors` [method](https://github.com/Avaiga/taipy-config/blob/develop/stubs/generate_pyi.py#L126). Could you add the change there?

OK, I've done this.  The generated `config.pyi` file is included in the PR (this is the output of running the generator).  black did some reformatted of the generator.

**Review by jrobinAV — APPROVED** [review]
Thank you!

**Pull request merged**
