### PR TITLE
chore: Add property methods to pyi file

### PR DESCRIPTION
**Pull request by joaoandre-avaiga**
I've added all the methods(including property methods) into the pyi file. Please make sure these are the methods we want to display. If any needs to be excluded, let me know.

### CODE REVIEW

**Review by jrobinAV — CHANGES_REQUESTED** [review]
Hi, 
Here, all the methods and attributes of all sections (ScenarioConfig, PipelineConfigs, etc...) are exposed. That is not the expected behavior.
We want to expose the methods and attributes of Config class that are dynamically injected from taipy-core.

In practice, we just want to expose the section accessors:
```
    @property
    def data_nodes(self) -> Dict[str, DataNodeConfig]:
        """"""

    @property
    def tasks(self) -> Dict[str, TaskConfig]:
        """"""

    @property
    def pipelines(self) -> Dict[str, PipelineConfig]:
        """"""

    @property
    def scenarios(self) -> Dict[str, ScenarioConfig]:
        """"""

    @property
    def job_config(self) -> JobConfig:
        """"""
```

I don't know how to change this since I don't really understand the code in `generate_pyi.py` module. We can have a talk if my comment is not clear.

**Comment by joaoandre-avaiga** [comment]
> Refere

Unfortunatelly, theres only two properties(tasks and pipelines) define in our config classes. So I've decided to generate the acessors this way. If you think of a better solution, let me know and we can change it

**Review by jrobinAV — COMMENTED** [review]
I believe the issue is even more difficult to resolve than your proposal. 
The accessors to expose in the pyi file are not the ones you expose The return type is incorrect, it should be a dict.
 
The ones to expose are dynamically injected in `src/taipy/config/__init__.py`, on lines 65 and 67. The `attribute_name` parameter is turned into an accessor method to return the dict of Sections.
We can eventually add a new parameter to the _inject_section to inject the documentation associated to the accessor name that is called `attribute_name`.

**Comment by joaoandre-avaiga** [comment]
> I believe the issue is even more difficult to resolve than your proposal. The accessors to expose in the pyi file are not the ones you expose The return type is incorrect, it should be a dict.
> 
> The ones to expose are dynamically injected in `src/taipy/config/__init__.py`, on lines 65 and 67. The `attribute_name` parameter is turned into an accessor method to return the dict of Sections. We can eventually add a new parameter to the _inject_section to inject the documentation associated to the accessor name that is called `attribute_name`.

Ive adjusted the templates. Let me know what do you think.

**Review by jrobinAV — APPROVED** [review]
Neat !

**Pull request merged**
